### ISSUE TITLE
Feature: variable width output

### ISSUE THREAD

**Issue by weebney** [usgraphics/TR-100#2]
Variable width output to prevent overflow when a value is longer than expected. Will enable the ability to support more platforms with behavior not consistent with Debian.

![An example of overflow](https://pbs.twimg.com/media/GPm_L5gXEAAiDGD?format=png&name=small)

**Comment by neilpanchal** [comment]
Thank you for the PR. Hey, I was thinking about this a bit more:

--

![CleanShot 2024-06-09 at 07 51 05@2x](https://github.com/usgraphics/TR-100/assets/8161031/339bd6c6-298d-4151-a271-990f569ee0cd)
--


What do you think about this: 1) We provide users with information about the system in robust way 2) We provide a template example that the users *must* adjust (including the width) instead of the library doing it for them? 

My concern is that over time, this thing will get super bloated with dynamic adjustments and various neat things that are wonderful additions, but they fixate the code into a rigid thing. I want users to take our template and if it looks ugly, for example too short a width, then we let them figure it out on how to fix it in their template.

So may be we split the script into 2 segments. System info(our responsibility) and Template(user's responsibility). And encourage users to edit the template to suit their system. Even delete the `$report_title` variable.

Open for thoughts.

**Comment by weebney** [comment]
I think an idiom like this could be pretty interesting:

```console
$ info_script > display_script
```

I'm not sure if you can see the vision now, but I can mock something up this afternoon.

**Comment by neilpanchal** [comment]
Yes! This is very UNIX-like.

**Comment by weebney** [comment]
@neilpanchal #3 has a working PoC of the behavior described above

**Comment by neilpanchal** [comment]
Did a quick glance, looks amazing. Thank you so much! I'll take a look at it in detail and respond back.

**Comment by alterae** [comment]
I think if longer lines are supported it is also important to somehow support line-wrapping, so that long lines do not overflow the terminal, especially in narrower terminal windows (i.e. 80x25).

**Comment by neilpanchal** [comment]
Sorry for radio silence, the more I think about this project, the more it feels like we should use existing work from projects like Fastfetch and build a theme for it. On the other hand, it's nice to have simplicity of bash with complete control over the customization. 

Still not sure which direction we should take.
