### ISSUE TITLE
Rsync doesn't work if .bashrc invokes machine report

### ISSUE THREAD

**Issue by neilpanchal** [usgraphics/TR-100#8]
![CleanShot 2024-06-10 at 22 37 43@2x](https://github.com/usgraphics/TR-100/assets/8161031/6cf3387c-ae63-44bc-aa8c-4d1a5efd3dce)

I can transfer files `server` -> `local` fine. But when sending files to a remote server with `.machine_report.sh` in `.bashrc` file, I get this error. Removing machine report from loading restores functionality of rsync.

**Comment by k-lar** [comment]
I don't think there's a way to fix this inside the script itself. Rsync runs `.bashrc` when connecting to another host and it doesn't play well when there's anything in there that produces output. [Here's more info on that.](https://unix.stackexchange.com/a/257613/73271)

The best way to solve this is to add this line at the top of `.bashrc`:

```bash
# If not running interactively, don't do anything
[[ $- != *i* ]] && return
```

Some distros do this already by default and it also solves problems with scp and sftp.

**Comment by k-lar** [comment]
I have changed my stance on this issue back to "shouldn't be our problem". Adding that line of code to the script has some weird effects and it causes inconsistencies and when I tried to make it work just when it's sourced in `.bashrc` it started complaining about bad substitution from sourcing /etc/os-release and printing the info.

Adding this to the script itself introduces lots of complexity that shouldn't be there in the first place, since this issue only pops up specifically when the script is used inside `.bashrc` and trying to use rsync/scp/sftp without the proper safeguards most distros already provide by default. I think instead of fixing this with the script, we provide the documentation and a simple explanation why this line of code needs to be at the top of the user's `.bashrc`:

```bash
# If not running interactively, don't do anything
[[ $- != *i* ]] && return
```

I have modified the README.md in my fork to reflect this.

**Comment by neilpanchal** [comment]
Thanks! Added your suggestion to the installation instructions.
